add support for custom post-install scripts
mbround18/valheim-docker pull request #400
Opened 2021-06-27 20:35 UTC by AGhost-7

# Description
Adds a script hook to define custom scripts after the installation completes. This allows me to copy from a ConfigMap in kubernetes the configuration files for valheim plus et al. Example post-install script:

```
#!/usr/bin/env bash
set -ex

rm -rf /home/steam/valheim/BepInEx/config
cp -r /home/steam/bep-config /home/steam/valheim/BepInEx/config
chown -R 1000:1000 /home/steam/valheim/BepInEx/config
```

Where `/home/steam/bep-config` is a volume in kubernetes pointing to a ConfigMap.

## Contributions

- I changed the startup script because I couldn't attach extra logic between the mod installation and server startup.
- Added logic executes all scripts under `/start-valheim-post-install.d/` before the valheim server starts.

## Checklist

- [ ] I added one or multiple labels which best describes this PR.
- [x] I have tested the changes locally.
- [ ] This PR has a reviewer on it.
- [x] I have validated my changes in a docker container and on Ubuntu. (Only needed for Odin or Docker Changes)

2021-06-28 17:59 UTC, mbround18 commented
Are these to be executed as root or the steam user?

2021-06-28 18:09 UTC, AGhost-7 commented
For my use case being executed as the steam user worked fine. I'm also using this to install additional plugins such as epic loot which doesn't seem to install correctly due to its non-standard structure.

2021-06-28 18:19 UTC, mbround18 requested changes

2021-06-28 18:19 UTC, mbround18 commented on src/scripts/start_valheim.sh
> +if [ -d /start-valheim-post-install.d/ ]; then
Mind of we change up the dir name and add quotes? 

Quotes for standardization and dir name for simplification. 

```bash
if [ -d "/valheim-post-install.d/" ]; then
  log "Executing post-install scripts"
  find /valheim-post-install.d/ -type f -executable -exec {} \;
fi
```

2021-06-29 05:47 UTC, mbround18 commented
I do have a question, unrelated to this PR, why not mount your config map to `/home/steam/valheim/BepInEx/config` ?

2021-06-29 13:18 UTC, AGhost-7 commented
There's already a mount in `/home/steam/valheim`, wasn't working for me on k3s.

2021-06-29 22:05 UTC, merged