ADD: Optional Public IP in Webhook notifications
mbround18/valheim-docker pull request #510
Opened 2022-01-19 22:27 UTC by apeabody

# Description
Adds a new environmental option WEBHOOK_INCLUDE_PUBLIC_IP which adds the world visible public IP of the server to the webhook notification (default is disabled, current behavior).  Useful for servers without static IPs.

## Contributions

- I added the new feature Optional Public IP in Webhook notifications.

## Checklist

- [X] I added one or multiple labels which best describes this PR.
- [X] I have tested the changes locally.
- [ ] This PR has a reviewer on it.
- [Ubuntu] I have validated my changes in a docker container and on Ubuntu. (Only needed for Odin or Docker Changes)

2022-01-19 23:32 UTC, mbround18 commented on src/odin/notifications/mod.rs
> +
Lets try and rip tokio out of there please, thats a large lib to include just for one http request. Use the already included lib of reqwest via something like this:

```rust

let body = reqwest::blocking::get("https://api.ipify.org?format=json").unwrap()
    .text().unwrap();
```

2022-01-19 23:33 UTC, mbround18 commented on src/odin/Cargo.toml
> +tokio = { version = "1", features = ["full"] }
Please see https://docs.rs/reqwest/0.11.9/reqwest/blocking/index.html

2022-01-19 23:34 UTC, mbround18 requested changes
Hey thanks for the PR! I have included some comments.

2022-01-20 02:10 UTC, apeabody commented
Thanks @mbround18! I was able to greatly simplify as suggested using `reqwest::blocking::get("https://api.ipify.org")`.

2022-01-22 20:10 UTC, mbround18 commented
Hey @apeabody, for some reason github isnt applying the repo secrets to your branch. Ill merge this into a repo specific branch and give it a while.

2022-01-22 20:10 UTC, merged