Refactored to derive
mbround18/valheim-docker pull request #651
Opened 2023-01-17 15:36 UTC by mbround18

# Description

## Contributions

- Upgraded Deps
- Added clap derive (and upgraded to clap 4.x)
- Refactored to use clap derive across the whole code for ease of use

## Checklist

- [ ] I added one or multiple labels which best describes this PR.
- [ ] I have tested the changes locally.
- [ ] This PR has a reviewer on it.
- [ ] I have validated my changes in a docker container and on Ubuntu. (Only needed for Odin or Docker Changes)

2023-01-17 16:37 UTC, CosmicHorrorDev requested changes
Lots of small stuff. Some important and some less so

Great to see things switched over to `clap` derive though :tada:

2023-01-17 16:37 UTC, CosmicHorrorDev commented on src/odin/cli.rs
> +    #[arg(short, long, value_name = "NAME", default_value_t = {"Valheim powered by Odin".to_string()})]
```suggestion
    #[arg(short, long, default_value_t = {"Valheim powered by Odin".to_string()})]
```

Also all of these `String` default values could use `String::from()` to avoid having to use the block aka `{...}`, but I'm fine either way

2023-01-17 16:37 UTC, CosmicHorrorDev commented on src/odin/cli.rs
> +    #[arg(short, long, value_name = "SERVER_EXECUTABLE_PATH", default_value_t = {format!("./{}", crate::constants::VALHEIM_EXECUTABLE_NAME)})]
```suggestion
    #[arg(long, value_name = "SERVER_EXECUTABLE_PATH", default_value_t = format!("./{}", crate::constants::VALHEIM_EXECUTABLE_NAME))]
```

2023-01-17 16:37 UTC, CosmicHorrorDev commented on src/odin/cli.rs
> +    #[arg(short, long, value_name = "PORT", default_value_t = 2456)]
```suggestion
    #[arg(short, long, default_value_t = 2456)]
```

2023-01-17 16:37 UTC, CosmicHorrorDev commented on src/odin/cli.rs
> +    port: u32,
Unlikely to matter unless someone tries to set a really high port, but I think this could just be a `u16` since that's the max range of a port

2023-01-17 16:37 UTC, CosmicHorrorDev commented on src/odin/cli.rs
> +    #[arg(short, long, value_name = "WORLD", default_value_t = {"Dedicated".to_string()})]
```suggestion
    #[arg(short, long, default_value_t = {"Dedicated".to_string()})]
```

2023-01-17 16:37 UTC, CosmicHorrorDev commented on src/odin/cli.rs
> +    #[arg(short, long, value_name = "PASSWORD", default_value_t = {"P@ssw0rd!".to_string()})]
```suggestion
    #[arg(short = 's', long, default_value_t = {"P@ssw0rd!".to_string()})]
```

2023-01-17 16:37 UTC, CosmicHorrorDev commented on src/odin/cli.rs
> +    #[arg(short, long, value_name = "PUBLIC", default_value_t = false)]
```suggestion
    #[arg(short = 'o', long)]
```

2023-01-17 16:37 UTC, CosmicHorrorDev commented on src/odin/cli.rs
> +  Install {},
```suggestion
  Install,
```

2023-01-17 16:37 UTC, CosmicHorrorDev commented on src/odin/cli.rs
> +  Start {},
```suggestion
  Start,
```

2023-01-17 16:37 UTC, CosmicHorrorDev commented on src/odin/cli.rs
> +  Stop {},
```suggestion
  Stop,
```

2023-01-17 16:37 UTC, CosmicHorrorDev commented on src/odin/cli.rs
> +    #[arg(short, long, default_value_t = false)]
```suggestion
    #[arg(short, long, conflicts_with("force"))]
```

2023-01-17 16:37 UTC, CosmicHorrorDev commented on src/odin/cli.rs
> +    #[arg(short, long, default_value_t = false)]
```suggestion
    #[arg(short, long)]
```

2023-01-17 16:37 UTC, CosmicHorrorDev commented on src/odin/cli.rs
> +pub struct Cli {
I would recommend adding

```rust
#[cfg(test)]
mod tests {
  use super::*;

  use clap::CommandFactory;

  #[test]
  fn asserts() {
    Cli::command().debug_assert();
  }
}
```

to the bottom of the file. `clap` gave up trying to enforce _everything_ at compile time, so they added `.debug_assert()` as a way to automatically test for some issues. This picked up on the conflicting names with some of the short args in `configure`

2023-01-17 16:37 UTC, CosmicHorrorDev commented on src/odin/Cargo.toml
> +clap = { version = "4.1.1", features = [ "derive" ] }
```suggestion
clap = { version = "4.1.1", features = [ "derive", "env" ] }
```

2023-01-17 16:37 UTC, CosmicHorrorDev commented on src/odin/cli.rs
> +    #[arg(short, long, value_name = "TITLE", default_value_t = {"Broadcast".to_string()})]
```suggestion
    #[arg(long, default_value_t = {"Broadcast".to_string()})]
```

2023-01-17 16:37 UTC, CosmicHorrorDev commented on src/odin/cli.rs
> +    #[arg(short, long, value_name = "MESSAGE", default_value_t = {"Test Notification".to_string()})]
```suggestion
    #[arg(default_value_t = {"Test Notification".to_string()})]
```

2023-01-17 16:37 UTC, CosmicHorrorDev commented on src/odin/cli.rs
> +    #[arg(short, long, value_name = "WEBHOOK_URL")]
```suggestion
    #[arg(long, env)]
```

I added `env` here so that `clap` would automatically pick up on whatever value `WEBHOOK_URL` is set to, but it's probably handled in the code separately already, I was just too lazy to check :sweat_smile:

2023-01-17 16:37 UTC, CosmicHorrorDev commented on src/odin/cli.rs
> +    // webhook_include_public_ip: bool,
Is this supposed to be commented out?

2023-01-17 16:37 UTC, CosmicHorrorDev commented on src/odin/cli.rs
> +    #[arg(short, long)]
```suggestion
    #[arg(long)]
```

2023-01-17 16:37 UTC, CosmicHorrorDev commented on src/odin/cli.yaml
> -              Title of the message block (required by discord & generic webhook, automatically supplied, default: "Broadcast")
I believe this whole file can be deleted now

2023-01-17 16:37 UTC, CosmicHorrorDev commented on src/odin/commands/backup.rs
> +      error!("Failed to create backup file at {}", &output);
```suggestion
      error!("Failed to create backup file at {output}");
```

2023-01-17 16:37 UTC, CosmicHorrorDev commented on src/odin/commands/notify.rs
> +  let webhook_url = env::var("WEBHOOK_URL").unwrap_or_else(|_| webhook_url.unwrap_or_default());
Ah yep, I found it! This can just be handled by `clap`. Same for all the other env vars

2023-01-17 16:37 UTC, CosmicHorrorDev commented on src/odin/commands/configure.rs
> +}
You could use a `struct` for the `Configure` variant of `cli::Commands` to avoid duplicating the definition here. E.g.

```rust
// src/cli.rs
pub struct Configuration {
    // Pull the values outside of the enum
}

pub enum Commands {
    /// Initializes Odin with its configuration variables.
    Configure(Configuration),
    ...
}
```

2023-01-17 16:37 UTC, CosmicHorrorDev commented on src/odin/commands/status.rs
> +    env::var("ADDRESS").unwrap_or_else(|_| {
Ditto on letting `clap` handle env vars

2023-01-17 16:37 UTC, CosmicHorrorDev commented on src/odin/commands/update.rs
> +  }
This doesn't have to be handled explicitly after the `conflicts_with()` suggestion above. If you still want to keep it as a sanity check then it could just be

```rust
assert!(!check || !force, "Woah! You can't check and force at the same time! Please choose one!");
```

2023-01-17 16:37 UTC, CosmicHorrorDev commented on src/odin/constants.rs
> +// pub const VERSION: &str = env!("CARGO_PKG_VERSION");
Can just be removed if unused

2023-01-17 16:37 UTC, CosmicHorrorDev commented on src/odin/files/config.rs
> +impl From<Configuration> for ValheimArguments {
Yay trait impls!

2023-01-17 16:37 UTC, CosmicHorrorDev commented on src/odin/files/config.rs
> +      password: env::var("PASSWORD").unwrap_or(value.password),
Ditto on letting `clap` handle env vars

2023-01-17 16:37 UTC, CosmicHorrorDev commented on src/odin/main.rs
> +  // }
Looks like all of this can be removed at this point?

2023-01-17 18:33 UTC, mbround18 commented on src/odin/main.rs
> +  // }
yee

2023-01-19 15:45 UTC, mbround18 commented on src/odin/cli.rs
> +    // webhook_include_public_ip: bool,
yes

2023-01-20 20:05 UTC, CosmicHorrorDev submitted a review, later dismissed
Everything looks good enough to me :+1:

2023-01-21 08:27 UTC, mbround18 commented
Will be testing with `mbround18/valheim:sha-9ef47e4` soon for validation before merging

2023-01-26 01:16 UTC, mbround18 commented
Damn invalid values for public flag, changing it up to keep the syntax

2023-02-17 22:07 UTC, mbround18 commented
This PR will be merged Tuesday the 21st

2023-02-27 00:08 UTC, merged